version: "3"
services:
  mqtt:
    image: toke/mosquitto
    network_mode: bridge
    container_name: mqtt
    expose:
    - 1883
    ports:
    - 1883:1883
    restart: unless-stopped
  subscriber:
    network_mode: host
    build: .
    command: "python3 src/main.py"
    #command: "streamlit run src/streamlit_sistema.py"
    ports:
      - "8501:8501"
    volumes:
      - "./src:/usr/src/app/src"
  streamlit:
    network_mode: host
    build: .
    command:  "streamlit run src/streamlit_sistema.py"
    #command: "streamlit run src/streamlit_sistema.py"
    ports:
      - "8501:8501"
    volumes:
      - "./src:/usr/src/app/src"
